// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  test: false,
  version: env.npm_package_version,
  serverUrl: '/api',
  defaultLanguage: 'en',
  supportedLanguages: [ 'en', 'el'],
  eth: {
    ethRpcUrl: 'https://0x.bloomen.io/rpc/telsius/wallet',
    ethBlockPollingTime: 4000,
    transactionStatusPollingTime: 2000,
    transactionCallDelayTime: 2000,
    hdMagicKey: 'H2020_Bloomen',
    generalSeed: 'kit mother damage noise monkey appear peanut come razor vacant story water',
    web3Options: {
      transactionConfirmationBlocks: 2,
      transactionPollingTimeout: 10000
    },
    contractConfig: {
      default: {
        value: 0,
        gasPrice: 0,
        gas: 9999999
      },
      networkId: '83584648538'
    }
  }
};
